terror: print the stack in terror.Log()
In TiDB, terror.Log(err) is called when we expect the error to be nil
and get rid of the annoying golint check.
Sometimes the error is not nil as expected, so it's better to print the
stack to find why